const productos = [{
    "id": 1,
    "nombre": "Pino",
    "img": "img/productos/Pino.jpg",
    "precio": 1500,
    "categoria": "Arboles",
    "tipo": "planta de exterior",
    "oferta": false,
    },{
    "id": 2,
    "nombre": "Santa Rita",
    "img": "img/productos/SantaRita.jpg",
    "precio": 4000,                                 //con el descuento quedaria 3200
    "categoria": "Planta",
    "tipo": "planta de interior",
    "oferta": true,
    },{
    "id": 3,
    "nombre": "Erica",
    "img": "img/productos/erica.jpg",
    "precio": 500,
    "categoria": "Arbusto",
    "tipo": "planta de exterior",
    "oferta": false,
    },{
    "id": 4,
    "nombre": "Latania",
    "img": "img/productos/latania.jpg",
    "precio": 6500,
    "categoria": "Palmera",
    "tipo": "planta de exterior",
    "oferta": false,
    },{
    "id": 5,
    "nombre": "Lavanda",
    "img": "img/productos/lavanda.jpg",
    "precio": 900,
    "categoria": "Floral",
    "tipo": "planta de exterior",
    "oferta": false,
    },{
    "id": 6,
    "nombre": "Rosales",
    "img": "img/productos/rosales.jpg",
    "precio": 4500,
    "categoria": "Floral",
    "tipo": "planta de exterior",
    "oferta": false,
    },{
    "id": 7,
    "nombre": "Costilla de Adan",
    "img": "img/productos/costilla-adan.jpg",
    "precio": 1500,                                 //con el descuento quedaria en 1200
    "categoria": "Planta",
    "tipo": "planta de Interior",
    "oferta": true,
    },{
    "id": 8,
    "nombre": "Limon 4 Estaciones",
    "img": "img/productos/limon.jpg",
    "precio": 3500,
    "categoria": "Arbol Frutal",
    "tipo": "planta de exterior",
    "oferta": false,
    },{
    "id": 9,
    "nombre": "Naranjo",
    "img": "img/productos/naranjo.jpg",
    "precio": 3500,                                      //con el descuento quedaria en 2800
    "categoria": "Arbol Frutal",
    "tipo": "planta de exterior",
    "oferta": true,
    },{
    "id": 10,
    "nombre": "Mandarino",
    "img": "img/productos/mandarino.jpg",
    "precio": 3500,
    "categoria": "Arbol Frutal",
    "tipo": "planta de exterior",
    "oferta": false,
    },{
    "id": 11,
    "nombre": "Maceta chica",
    "img": "img/productos/macetas.jpg",
    "precio": 150,                                  //con el descuento quedaria en 120
    "categoria": "accesorio",
    "tipo": "Ceramica",
    "oferta": true,
    },{ 
    "id": 12,
    "nombre": "Tierra Fertil",
    "img": "img/productos/tierra-fertil.jpg",
    "precio": 3500,
    "categoria": "tierra x 50kg",
    "tipo": "Orgánico",
    "oferta": false,
    },{
    "id": 13,
    "nombre": "Humus de Lombriz",
    "img": "img/productos/Humus-De-Lombriz.jpg",
    "precio": 300,
    "categoria": "tierra",
    "tipo": "Orgánico",
    "oferta": false,
    },{
    "id": 14,
    "nombre": "Maceta grande",
    "img": "img/productos/macetas.jpg",
    "precio": 200,
    "categoria": "accesorio",
    "tipo": "Plastico",
    "oferta": false,
    },{
    "id": 15,
    "nombre": "Tierra Fertil de Jardin",
    "img": "img/productos/tierra-fertil.jpg",
    "precio": 1500,                                 //con el descuento quedaria en 1200
    "categoria": "Tierra x 2kg",
    "tipo": "Orgánico",
    "oferta": true,
    }]
    